# Generated by Django 5.1.7 on 2025-05-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='db_schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
