# Generated by Django 5.1.7 on 2025-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_userdatabase_db_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='db_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
